apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: goserver
    spec:
      imagePullSecrets:
        - name: regcred

      volumes:
        - name: config
          configMap:
            name: configmap-family
            items: 
            - key: members
              path: myfamily.txt

      containers:
        - name: goserver
          image: "21lucasmessias/go-hello:v4"
          volumeMounts:
            - mountPath: "/go/family/"
              name: config
          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret